/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'rescue-centers': RescueCenter;
    content: Content;
    species: Species;
    quizzes: Quiz;
    games: Game;
    'game-scores': GameScore;
    sources: Source;
    glossary: Glossary;
    'agent-proposals': AgentProposal;
    'agent-runs': AgentRun;
    'user-submissions': UserSubmission;
    reactions: Reaction;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'rescue-centers': RescueCentersSelect<false> | RescueCentersSelect<true>;
    content: ContentSelect<false> | ContentSelect<true>;
    species: SpeciesSelect<false> | SpeciesSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    'game-scores': GameScoresSelect<false> | GameScoresSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    glossary: GlossarySelect<false> | GlossarySelect<true>;
    'agent-proposals': AgentProposalsSelect<false> | AgentProposalsSelect<true>;
    'agent-runs': AgentRunsSelect<false> | AgentRunsSelect<true>;
    'user-submissions': UserSubmissionsSelect<false> | UserSubmissionsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en' | 'de') | ('ru' | 'en' | 'de')[];
  globals: {
    'section-content': SectionContent;
  };
  globalsSelect: {
    'section-content': SectionContentSelect<false> | SectionContentSelect<true>;
  };
  locale: 'ru' | 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'translator' | 'viewer' | 'agent';
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Каталог реабилитационных центров (sealrescue.info). Поддерживается Агентом-1.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rescue-centers".
 */
export interface RescueCenter {
  id: number;
  /**
   * НЕ переводится — имя центра одинаково во всех локалях (правило глоссария).
   */
  name: string;
  slug: string;
  country: string;
  region?: string | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  /**
   * Соцсети центра: Instagram / Facebook / TikTok / LinkedIn / YouTube / VK / Telegram / X.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'linkedin' | 'youtube' | 'vk' | 'telegram' | 'x' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  operatingLanguages?: ('ru' | 'en' | 'de' | 'other')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'active' | 'unconfirmed' | 'link_broken' | 'needs_check';
  verificationScore?: number | null;
  lastCheckedAt?: string | null;
  /**
   * Показываем на странице: «Проверено агентом».
   */
  verifiedByAgentAt?: string | null;
  /**
   * Показываем на странице: «Проверено человеком».
   */
  verifiedByHumanAt?: string | null;
  sources?: (number | Source)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Источники для фактчекинга. trustLevel = allowlist (OWASP).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  url: string;
  type: 'official' | 'news' | 'social' | 'manual';
  /**
   * Официальным источникам — высокий trust; для критичных данных используем allowlist.
   */
  trustLevel?: number | null;
  lastFetchedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Статьи, новости, мемы, страницы (sealife.info).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content".
 */
export interface Content {
  id: number;
  type: 'article' | 'news' | 'meme' | 'page';
  title: string;
  /**
   * Canonical slug — общий для всех локалей (/ru/slug, /en/slug).
   */
  slug: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Темы для фильтра ленты/галереи (M1-T02). slug общий для локалей; подпись локализуется в коде (content/topics.ts), НЕ в content-локализации.
   */
  topics?: ('biology' | 'behavior' | 'conservation' | 'rescue' | 'humor' | 'science')[] | null;
  /**
   * Перелинковка sealife <-> sealrescue.
   */
  crossLink?: {
    rescueCenter?: (number | null) | RescueCenter;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * EU AI Act: маркировать AI-сгенерированный/переведённый контент.
   */
  aiGenerated?: boolean | null;
  /**
   * Integrity перевода (Агент 3). Заполняется автоматически.
   */
  localeStatus?:
    | {
        locale?: string | null;
        status?: ('current' | 'stale' | 'review') | null;
        sourceHash?: string | null;
        translatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility (WCAG 2.1 AA / EAA) + SEO. Заполнять обязательно.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Виды ластоногих (Тюленепедия, sealife.info).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "species".
 */
export interface Species {
  id: number;
  name: string;
  /**
   * Canonical slug — общий для локалей (/ru/species/slug, /en/species/slug).
   */
  slug: string;
  /**
   * Научное (латинское) имя. НЕ переводится (правило глоссария).
   */
  latin: string;
  /**
   * Охранный статус IUCN. Подпись локализуется в UI.
   */
  conservationStatus?: ('LC' | 'NT' | 'VU' | 'EN' | 'CR' | 'DD') | null;
  /**
   * Ареал.
   */
  region?: string | null;
  /**
   * Размер, напр. «≈ 1.3 м».
   */
  size?: string | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Короткие факты. Используются на карточке вида и в «Факте дня».
   */
  facts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  /**
   * EU AI Act: маркировать AI-сгенерированный/переведённый контент.
   */
  aiGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  questions?:
    | {
        question: string;
        options?:
          | {
              text: string;
              isCorrect?: boolean | null;
              id?: string | null;
            }[]
          | null;
        explanation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * EU AI Act: маркировать, если вопросы сгенерированы AI.
   */
  aiGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Мини-игры (sealife.info).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  title: string;
  /**
   * Canonical slug — общий для локалей (/ru/games/slug, /en/games/slug).
   */
  slug: string;
  excerpt?: string | null;
  /**
   * «Как играть»: управление и цель — текстом вне canvas (доступность).
   */
  how?: string | null;
  /**
   * Путь к встроенной статической игре из /public (напр. /games/seal-hunt-v1/index.html). Язык игры подставляется автоматически (?lang=). Пусто — пока без играбельного фрейма.
   */
  embed?: string | null;
  /**
   * Обложка игры: карточка в списке игр и (при showCover) заставка на странице. Пусто — декоративный плейсхолдер. Отдача через CDN/geo — M0-T04.
   */
  coverImage?: (number | null) | Media;
  /**
   * Показывать загруженную обложку на КАРТОЧКЕ в списке игр. Выкл — плейсхолдер (картинка сохраняется).
   */
  showCardCover?: boolean | null;
  /**
   * Показывать картинку-заставку над игрой на её странице. Выкл — сразу крупный игровой фрейм.
   */
  showCover?: boolean | null;
  /**
   * Вариант декоративной заставки (меняет оттенок). Любое целое число.
   */
  coverSeed?: number | null;
  /**
   * Порядок в списке игр: меньше — выше.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Анонимные результаты мини-игр (лидерборд). PII не хранится.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-scores".
 */
export interface GameScore {
  id: number;
  game: number | Game;
  /**
   * Недельный односторонний ключ игрока (не сырой seed). Идентичность строки.
   */
  playerKey: string;
  /**
   * EN base имени (без суффикса) — для уникальности дисплея.
   */
  baseAlias: string;
  /**
   * 0/1 — без суффикса; ≥2 — добавляется к имени при коллизии («… 2»).
   */
  suffix: number;
  /**
   * EN display-имя (base + суффикс) — подпись в админке.
   */
  alias: string;
  /**
   * Locale-независимые части имени — имя рисуется на клиенте на языке зрителя.
   */
  nameParts:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  score: number;
  durationMs: number;
  board: 'desktop' | 'mobile';
  /**
   * ISO-неделя (YYYY-Www) — для еженедельного сброса доски.
   */
  season: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Словарь терминов и тюль-сленга: ru → перевод. Для переводчиков и Агента 3.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary".
 */
export interface Glossary {
  id: number;
  /**
   * Исходный термин на ru (ключ, общий для всех локалей). Не переводится.
   */
  source: string;
  /**
   * Эквивалент в текущей локали (en сейчас, de позже).
   */
  translation?: string | null;
  category: 'term' | 'slang' | 'meme';
  /**
   * Альтернативные формы текущей локали (на ru: тюласты, тюль-малыш; на en: seal baby). Переключай локаль в админке — список свой для каждого языка.
   */
  variants?:
    | {
        value: string;
        /**
         * Тег варианта. Пусто = берётся тег всей записи (category выше).
         */
        category?: ('term' | 'slang' | 'meme') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Контекст/пояснение: «по контексту», «уточнять вид», смысл жаргона.
   */
  note?: string | null;
  /**
   * Не переводить (имена/бренды/телефоны). Подсказка для integrity-проверки Агента 3.
   */
  doNotTranslate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Очередь на ревью. Агенты предлагают — человек решает.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-proposals".
 */
export interface AgentProposal {
  id: number;
  summary: string;
  proposalType:
    | 'center_update'
    | 'new_center'
    | 'news_draft'
    | 'broken_link'
    | 'stale_translation'
    | 'seo_suggestion'
    | 'other';
  /**
   * slug целевой коллекции, напр. rescue-centers
   */
  targetCollection?: string | null;
  /**
   * id целевого документа (если обновление)
   */
  targetId?: string | null;
  /**
   * Что меняется: { field: { from, to } }
   */
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Доказательства: URL, снапшот HTML, цитаты
   */
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sources?: (number | Source)[] | null;
  confidence?: number | null;
  status: 'pending' | 'approved' | 'rejected' | 'applied';
  reviewerNotes?: string | null;
  agentRun?: (number | null) | AgentRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs".
 */
export interface AgentRun {
  id: number;
  agentName: 'researcher' | 'content_admin' | 'translator' | 'sysadmin' | 'seo';
  status?: ('running' | 'success' | 'failed') | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  proposalsCreated?: number | null;
  /**
   * Стоимость прогона, USD (бюджет-контроль AI API).
   */
  cost?: number | null;
  logs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Присланное пользователями: мем-подписи, правки, новые центры, жалобы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-submissions".
 */
export interface UserSubmission {
  id: number;
  summary?: string | null;
  submissionType: 'meme_caption' | 'correction' | 'new_center' | 'report' | 'other';
  content: string;
  relatedCollection?: string | null;
  relatedId?: string | null;
  /**
   * НЕОБЯЗАТЕЛЬНО. Ник в TG/VK для ответа. Email не запрашиваем (минимизация данных).
   */
  contactHandle?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  /**
   * collection:id, напр. content:123
   */
  key: string;
  emoji: string;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'rescue-centers';
        value: number | RescueCenter;
      } | null)
    | ({
        relationTo: 'content';
        value: number | Content;
      } | null)
    | ({
        relationTo: 'species';
        value: number | Species;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'game-scores';
        value: number | GameScore;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'glossary';
        value: number | Glossary;
      } | null)
    | ({
        relationTo: 'agent-proposals';
        value: number | AgentProposal;
      } | null)
    | ({
        relationTo: 'agent-runs';
        value: number | AgentRun;
      } | null)
    | ({
        relationTo: 'user-submissions';
        value: number | UserSubmission;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rescue-centers_select".
 */
export interface RescueCentersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  region?: T;
  website?: T;
  email?: T;
  phone?: T;
  address?: T;
  location?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  operatingLanguages?: T;
  description?: T;
  status?: T;
  verificationScore?: T;
  lastCheckedAt?: T;
  verifiedByAgentAt?: T;
  verifiedByHumanAt?: T;
  sources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_select".
 */
export interface ContentSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  topics?: T;
  crossLink?:
    | T
    | {
        rescueCenter?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  aiGenerated?: T;
  localeStatus?:
    | T
    | {
        locale?: T;
        status?: T;
        sourceHash?: T;
        translatedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "species_select".
 */
export interface SpeciesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  latin?: T;
  conservationStatus?: T;
  region?: T;
  size?: T;
  excerpt?: T;
  body?: T;
  facts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  coverImage?: T;
  aiGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  questions?:
    | T
    | {
        question?: T;
        options?:
          | T
          | {
              text?: T;
              isCorrect?: T;
              id?: T;
            };
        explanation?: T;
        id?: T;
      };
  aiGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  how?: T;
  embed?: T;
  coverImage?: T;
  showCardCover?: T;
  showCover?: T;
  coverSeed?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-scores_select".
 */
export interface GameScoresSelect<T extends boolean = true> {
  game?: T;
  playerKey?: T;
  baseAlias?: T;
  suffix?: T;
  alias?: T;
  nameParts?: T;
  score?: T;
  durationMs?: T;
  board?: T;
  season?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  url?: T;
  type?: T;
  trustLevel?: T;
  lastFetchedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary_select".
 */
export interface GlossarySelect<T extends boolean = true> {
  source?: T;
  translation?: T;
  category?: T;
  variants?:
    | T
    | {
        value?: T;
        category?: T;
        id?: T;
      };
  note?: T;
  doNotTranslate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-proposals_select".
 */
export interface AgentProposalsSelect<T extends boolean = true> {
  summary?: T;
  proposalType?: T;
  targetCollection?: T;
  targetId?: T;
  diff?: T;
  evidence?: T;
  sources?: T;
  confidence?: T;
  status?: T;
  reviewerNotes?: T;
  agentRun?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs_select".
 */
export interface AgentRunsSelect<T extends boolean = true> {
  agentName?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  proposalsCreated?: T;
  cost?: T;
  logs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-submissions_select".
 */
export interface UserSubmissionsSelect<T extends boolean = true> {
  summary?: T;
  submissionType?: T;
  content?: T;
  relatedCollection?: T;
  relatedId?: T;
  contactHandle?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  key?: T;
  emoji?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Переопределения заголовка/лида/обложки разделов. Пустое поле = значение из кода. Сами разделы (маршруты) добавляются только в коде.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-content".
 */
export interface SectionContent {
  id: number;
  /**
   * Не больше одной записи на раздел (лишние игнорируются рендером).
   */
  overrides?:
    | {
        section:
          | 'articles'
          | 'news'
          | 'memes'
          | 'quizzes'
          | 'games'
          | 'species'
          | 'what-to-do'
          | 'rescue-centers'
          | 'rescue-news'
          | 'report'
          | 'rescue-quest';
        /**
         * H1 страницы раздела. Пусто — из кода.
         */
        title?: string | null;
        /**
         * Лид-абзац раздела и текст карточки в хабе. Пусто — из кода.
         */
        intro?: string | null;
        /**
         * Обложка карточки раздела в хабе на главной. Пусто — карточка без картинки.
         */
        cover?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-content_select".
 */
export interface SectionContentSelect<T extends boolean = true> {
  overrides?:
    | T
    | {
        section?: T;
        title?: T;
        intro?: T;
        cover?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}